name: Deploy MkDocs Documentation
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin

      - name: Deploy to GitHub Pages
        run: |
          cd sys_config
          pip install mkdocs-with-pdf pydyf==0.8.0 weasyprint==61.2
          mkdocs gh-deploy --force
